### ISSUE TITLE
Jar-in-Jar Dependencies causing `java.lang.StringIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by ApexModder** [covers1624/WorkspaceTool#8]
When setting up a workspace and some of the included projects use the Jar-in-Jar (_JiJ_) system, WST will crash when it comes time to process the IDEA modules, causing `java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 5`.

This is due to the JiJ dependencies declared in the dependencies block not having `_mapped_` in the file names resulting in your "find the dependency version" logic to return `-1` and crash WST with index out of bounds.

<details>
<summary>Debug files</summary>

_Location in code that is causing the issue_
_https://github.com/covers1624/WorkspaceTool/blob/master/subprojects/forge/src/main/java/net/covers1624/wt/forge/ForgeExtension.java#L171-L172_

_Preview of erroring file when run via IDEA_
![image](https://user-images.githubusercontent.com/29412632/187056282-de74c07f-d477-4727-bb61-69f743600cce.png)

_Log file after running with JiJ dependencies_
[debug.log](https://github.com/covers1624/WorkspaceTool/files/9439047/2022-08-28-3.log)

</details>

A potential fix would maybe, be to ignore any JiJ dependencies. These kinds of dependencies are only used by ForgeGradle when building the compiled mod jar and are unrelated to the project setup, these dependencies are also included into the project using the normal gradle include lines
`implementation fg.deobf('my.package:my-dep:version')`

**Comment by covers1624** [comment]
Should be Fixed in: https://github.com/covers1624/WorkspaceTool/commit/fe833615583f733ac5aa3e6cccee76613bec95fe
